version: "3.7"
services:
  mysqlDb:
    container_name: mysqlDb
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootDb
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - inatel

  stock:
    container_name: stock
    image: lucasvilela/stock-manager
    ports:
      - "8080:8080"
    networks:
      - inatel

networks:
  inatel:
    driver: bridge